### ISSUE TITLE
How can I encrypt my data "segments" with AWS KMS

### ISSUE THREAD

**Issue by AhmedTouil94** [aws-solutions/video-on-demand-on-aws#102]
I use this VOD solution and i have my segments on was cloud front and media convert output.
I need to encrypt my data and decrypt it on a mobile application.
Can someone help me, please!
thanks.

**Comment by tomnight** [comment]
DRM is the best way to protect video content, there was a similar request in the following issue and some details which will hopefully help:

https://github.com/awslabs/video-on-demand-on-aws/issues/91

To get started I would look here: https://docs.aws.amazon.com/mediaconvert/latest/ug/implementing-digital-rights-management-drm.html

the short version is you need a DRM provider or as per the documentation you can setup you own encryption but this only works with HLS.

Because of the Provider requirement this isn't part of the solution but we will review this topic at the next release.

**Comment by AhmedTouil94** [comment]
what about if i want to use server-side encryption with key using KMS and decrypt it on my application with a key?

**Comment by tomnight** [comment]
https://aws.amazon.com/blogs/networking-and-content-delivery/serving-sse-kms-encrypted-content-from-s3-using-cloudfront/

This artificial should help set this up, not sure what impact this would have on trying to serve HLS or DASH segments as the lambda@edge would be called for every segment. this would also have a significant cost implication.  you could try setting up sever side encryption on just the index files (eg for HLS just do this for the .m2u8 files and the ts segments.

**Comment by AhmedTouil94** [comment]
@tomnight 
thank you for your proposition,
it works for me with txt files but with hls no.

**Comment by tomnight** [comment]
Looking at the MediaConvert documentation its looks like you have to encrypt the files at the encoding stage:

https://docs.amazonaws.cn/en_us/mediaconvert/latest/ug/implementing-server-side-encryption.html

If this is the case you will need to update the job templates and possibly the encode lambda function to accommodate the changes. I would start with setting up a test job to create a set of HLS and go from there.

**Comment by AhmedTouil94** [comment]
@tomnight 
I apply that solution "Server-side-encryption" and I am able to encrypt my files.
my issue now is that I want to decrypt my files with my mobile application.
have you an idea about that?

**Comment by tomnight** [comment]
That will very much depend on which platform you are building you mobile app on. I'm afraid I don't have much insight for you on that subject sorry. You'll need a compatible video player that can decrypt the segments before playing them.

**Comment by AhmedTouil94** [comment]
@tomnight 
ok
thanks for your time
