### ISSUE TITLE
Unable to update the stack to the recent available

### ISSUE THREAD

**Issue by mzahidriaz** [aws-solutions/video-on-demand-on-aws#221]
**Describe the bug**
I have previous installation done on 2022-05-19
Now I want to update the stack and getting following error.

**Expected behavior**
Should be able to update the stack

- [us-west-2 ] Region: [e.g. us-west-2]

**Screenshots**
![image](https://github.com/aws-solutions/video-on-demand-on-aws/assets/2793322/3a8e03b5-7cdf-490a-9f0b-66997b07209b)

**Comment by raulmlamzn** [comment]
Thanks for reporting this issue @mzahidriaz. From the date you provided I'm guessing you are running an old version of the solution (v5.3.1?). Can you please confirm the version by checking in your AWS account, under CloudFormation > Stacks (you'll see a Video on Demand on AWS instance with stack and template details of your deployment including the version)?

**Comment by pruzicka** [comment]
I have the same problem, I'm running 5.2.0. Region eu-central-1. Thank you

**Comment by raulmlamzn** [comment]
This upgrade failure is expected since the solution moved to CDK in v6.0.0 per the release notes below, and you are trying to upgrade from v5.x.
https://github.com/aws-solutions/video-on-demand-on-aws/releases/tag/v6.0.0
(Upgrade path from old versions require a delete and re-deploy since moving to CDK)

However, you will be able to keep the S3 buckets, DynamoDB table, and CloudWatch logs created by the solution after you uninstall the stack. See notes in the Implementation Guide:
https://docs.aws.amazon.com/solutions/latest/video-on-demand-on-aws/uninstall-the-solution.html
