### ISSUE TITLE
Upgrading from v5.x to v6.x

### ISSUE THREAD

**Issue by deadmantfa** [aws-solutions/video-on-demand-on-aws#242]
**Describe the bug**
I am trying to upgrade the solution but got error (Check screenshot section)

I can delete and recreate the entire solution but needed to know would I be loosing all the videos already converted using the v5.x

**To Reproduce**
Follow the upgrade procedure. See the error

**Expected behavior**
Should Update the solutuion

**Please complete the following information about the solution:**
- [x] Version: v5.3.1
- [ ] Update Version:  v6.1.5

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [x] Region: ap-south-1
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? No

**Screenshots**

![image](https://github.com/aws-solutions/video-on-demand-on-aws/assets/1812611/5aae8fcc-d4c5-49c0-9f59-f0996a221560)

**Additional context**
NA

**Comment by raulmlamzn** [comment]
Hello @deadmantfa,
This upgrade failure is expected since the solution moved to CDK in v6.0.0 per the release notes below, and you are trying to upgrade from v5.3.1. 
https://github.com/aws-solutions/video-on-demand-on-aws/releases/tag/v6.0.0
However, you will be able to keep the S3 buckets, DynamoDB table, and CloudWatch logs created by the solution after you uninstall the stack. See notes in the Implementation Guide:
https://docs.aws.amazon.com/solutions/latest/video-on-demand-on-aws/uninstall-the-solution.html

**Comment by deadmantfa** [comment]
@raulmlamzn thank you for the quick response. I will have a look at the documentation again. Just worried that as I have live videos which my customers are using and hope there is no loss/downtime for them due to this change I am trying to make.
Thank you once again for pointing me to the right direction
