### ISSUE TITLE
HLS Audio workflow MP3, WAV files

### ISSUE THREAD

**Issue by abbasghulam** [aws-solutions/video-on-demand-on-aws#71]
We used this solutions for video and working as charming. 

Our requirements has changed now. We also need workflow for audio files i.e. **mp3, .wav** 

Can you please add this feature and estimated timeline if possible?

**Comment by tomnight** [comment]
Thats certainly something we could look into, can you explain the requirements in a little more details? 
what would be the inputs / outputs?

**Comment by endigo** [comment]
@tomnight Hello, in my case, I need to encode `.mp3` or `.wav` to Apple HLS format.

**Comment by nick-myers-dt** [comment]
@tomnight we're starting to work with AWS VOD for our video, and have identified audio needs as well.  We'd ideally like to use a single media pipeline, rather than set up additional services.  

We're looking at outputting video in HLS and DASH, packaged with DRM and Video.js for playback.

Audio-wise - 

- Input : MP3 or WAV
- Output: DASH, HLS, MP3 all packaged with DRM

**Comment by nodestorydev** [comment]
Hello - we are a media app and are using the Video on Demand template on AWS and it works well. But our app also needs to stream audio-only and we would request support an audio-only template. Input is mp3, wav output streaming mp3, wav, aac, Hls

**Comment by endigo** [comment]
@nick-myers-dt @nodestorydev Hello, I created a custom workflow to convert .MP3 or WAV files to HLS.

No need to change any config.
https://github.com/endigo/video-on-demand-on-aws
