### ISSUE TITLE
Migrate to AWS-CDK?

### ISSUE THREAD

**Issue by reinismu** [aws-solutions/video-on-demand-on-aws#88]
**Is your feature request related to a problem? Please describe.**
We use aws-cdk for our infrastructure and now it is tricky to integrate this in our stack.

**Describe the feature you'd like**
A way to easily use it with CDK. Maybe it is worth to rewrite it?

I could do `CfnInclude`, but it loses a lot of flexibility.

**Comment by kewur** [comment]
is there any update on the status of of the roadmap? CDK is gaining popularity, and I'm one of those would like to use this in my stacks

**Comment by morjoan** [comment]
At the moment, this is still on the roadmap but no exact time frame. In the meantime, I suggest looking at the Foundation version of the solution: https://github.com/awslabs/video-on-demand-on-aws-foundations/tree/main/deployment   
Though not as feature-rich as this solution, it has been implemented with CDK and might still be a good reference.

**Comment by amkuchta** [comment]
If it's of interest to anyone, I've started migrating this to the AWS CDK using TypeScript - if anyone wants to follow along, the code can be found on my fork:

https://github.com/amkuchta/video-on-demand-on-aws/tree/cdk-conversion

General layout is that I am going to use custom Constructs to define all of the resources, then tie them all together in the main `aws-vod-cdk-stack.ts` file.  In my head, that's the best way to organize this and make it easily maintainable.  I'm still a little bit new to the CDK, so I'm expecting some fumbles along the way.  I'll also be adding in items like a Cognito User & Identity Pool (because I need authentication / authorization for my app) and the ability to add custom tags, a title & description, and "poster" (thumbnail) images for each video (kind of like YouTube).

**Comment by mwleinad** [comment]
is the cdk migration ever happening? :( 
@amkuchta did you figure out some of the issues with your implementation?

**Comment by amkuchta** [comment]
@mwleinad I actually got it all working, but it grew in scope a little bit (and then life happened). I need to clean it up some, rebase it, and create a readme file on how to use the CDK for deployment

**Comment by mwleinad** [comment]
Thanks, good to know @amkuchta let me know if you end up doing that. We are also in the process of converting this to CDK.
did you try using this? 
https://docs.aws.amazon.com/cdk/v2/guide/use_cfn_template.html
and just build on top of the template?

**Comment by amkuchta** [comment]
@mwleinad I actually started a new CDK project from scratch and manually converted everything by hand; current code can be found here:

https://github.com/amkuchta/video-on-demand-on-aws/tree/cdk-conversion/aws-vod-cdk

**Comment by mwleinad** [comment]
@amkuchta looks like v6.0.0 supports CDK 
@tomnight looks like that's the case right?

**Comment by cassneal** [comment]
@mwleinad correct. 6.0 does.
